### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by NotZeetaa** [PixelOS-AOSP/official_devices#157]
## Name and Codename of the device you want to apply for 
```
Poco F3 (alioth)
```

## Device Tree sources

```
https://github.com/NotZeetaa/device_xiaomi_sm8250-common
https://github.com/NotZeetaa/device_xiaomi_alioth
https://github.com/projects-nexus/nexus_kernel_xiaomi_sm8250
https://github.com/NotZeetaa/vendor_xiaomi_sm8250-common
https://github.com/NotZeetaa/vendor_xiaomi_alitoh
```

## What ROM's do you maintain officially/unofficially
```
PixelOs (Unofficially)
```

## How long have you been building Custom ROMs
```
1 year
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@NotZeetaa
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-13-unofficial-pixelos-aosp-stable-24-09-2022.4497443/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/NexusKernelSm8250Channel/67
```

**Comment by kawaaii** [comment]
1. You haven't properly authored the commit https://github.com/projects-nexus/nexus_kernel_xiaomi_sm8250/commit/e0893cd992b0fbf0b6e9e1ce1053060b6b454351
2. I think the following commits are useless.
https://github.com/NotZeetaa/device_xiaomi_sm8250-common/commit/9099eac286ac2ffc95666e163b033b9b6ace9a9e
https://github.com/NotZeetaa/device_xiaomi_sm8250-common/commit/c20c2526c2c24b1113c7d75efb97e9bbc613cc95
https://github.com/NotZeetaa/device_xiaomi_sm8250-common/commit/65257ad4cedf474b99b6fcc2d3f80dd650f095e8
https://github.com/NotZeetaa/device_xiaomi_sm8250-common/commit/f61c0be80af62491ebb49c1b8afcfe33304a7dfa
3. The commit https://github.com/NotZeetaa/vendor_xiaomi_sm8250-common/commit/39e9084b61536c7e036d86e7d7e65599501cd273 is wrong. The path should have been "system" only instead of "system/system". Please fixit up.
4. Kernel commits are messy. Full of picks and reverts, for eg. you pick and then you revert the MGLRU.

**Comment by NotZeetaa** [comment]
> 1. You haven't properly authored the commit [projects-nexus/nexus_kernel_xiaomi_sm8250@e0893cd](https://github.com/projects-nexus/nexus_kernel_xiaomi_sm8250/commit/e0893cd992b0fbf0b6e9e1ce1053060b6b454351)
> 2. I think the following commits are useless.
>    [NotZeetaa/device_xiaomi_sm8250-common@9099eac](https://github.com/NotZeetaa/device_xiaomi_sm8250-common/commit/9099eac286ac2ffc95666e163b033b9b6ace9a9e)
>    [NotZeetaa/device_xiaomi_sm8250-common@c20c252](https://github.com/NotZeetaa/device_xiaomi_sm8250-common/commit/c20c2526c2c24b1113c7d75efb97e9bbc613cc95)
>    [NotZeetaa/device_xiaomi_sm8250-common@f61c0be](https://github.com/NotZeetaa/device_xiaomi_sm8250-common/commit/f61c0be80af62491ebb49c1b8afcfe33304a7dfa)
> 3. The commit [NotZeetaa/vendor_xiaomi_sm8250-common@39e9084](https://github.com/NotZeetaa/vendor_xiaomi_sm8250-common/commit/39e9084b61536c7e036d86e7d7e65599501cd273) is wrong. The path should have been "system" only instead of "system/system". Please fixit up.
> 4. Kernel commits are messy. Full of picks and reverts, for eg. you pick and then you revert the MGLRU.

Fixed.

**Comment by kawaaii** [comment]
Your commit history doesn't look right, please consider rebasing.

**Comment by NotZeetaa** [comment]
> Your commit history of kernel doesn't look right, please consider rebasing.

Done.

https://github.com/projects-nexus/nexus_kernel_xiaomi_sm8250/tree/rebase5

**Comment by NotZeetaa** [comment]
No answer yet?

**Comment by NotZeetaa** [comment]
Imma close it then, atleast u guys could say rejected or something...

**Comment by basamaryan** [comment]
@NotZeetaa Hey, my apologies regarding the silence, we have just been very busy irl. If you are still interested in maintaining the ROM, feel free to PM me on Telegram (t.me/Aryannn999)
