### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by popoA3M** [PixelOS-AOSP/official_devices#271]
## Name and Codename of the device you want to apply for 
```
Poco f5 / Redmi note 12 Turbo (marble)
```

## Device Tree sources

```
https://github.com/popoA3M/android_device_xiaomi_marble
https://github.com/popoA3M/android_device_xiaomi_marble-kernel
https://github.com/popoA3M/android_vendor_xiaomi_marble
```

## What ROM's do you maintain officially/unofficially
```
tequilaOS official
```

## How long have you been building Custom ROMs
```
August 2021
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@popoASM
```

### Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-unofficial-pixelos-aosp-stable-07-11-2023.4640451/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/Poco_F5Official/391
```

**Comment by cyberknight777** [comment]
After reviewing this, we noticed some things that stood out and as such are declining the application at this time.

We couldn't find any original changes made by you, which is something we would expect of a maintainer.

`AOSP_VERSION` isn't an existing variable, we would expect someone with experience building since 2021 to check the source to see if that variable existed.

SystemUIGoogle is no longer used, something that we would have expected you to check.

Per the reasons listed above, we can't accept you onto the team at this time as we don't believe you have enough experience to join the team just yet, however when you have gained this experience, feel free to apply again in the future.

Best regards,
The PixelOS Team
