### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AswinOP** [PixelOS-AOSP/official_devices#352]
## Name and Codename of the device you want to apply for 
```
POCO X4 Pro 5G/Redmi Note 11 Pro+ 5G (VEUX/PEUX)
```

## Device Tree sources

```
https://github.com/AswinOP/device_xiaomi_veux
https://github.com/aswinop/kernel_xiaomi_sm6375
https://gitlab.com/aswinop/vendor_xiaomi_veux 
```

## What ROM's do you maintain officially/unofficially
```
Project Matrixx ( Officially ) / Pixel OS ( Unofficially )
```

## How long have you been building Custom ROMs
```
Since last year ( 4 months )
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
Reverted a commit for play integrity
```

### Telegram username
```
iaswinop
```

### Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-unofficial-pixelos-aosp-19-02-2024.4645483/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/pocox4proofficial/430332
```

**Comment by cyberknight777** [comment]
https://github.com/AswinOP/kernel_xiaomi_sm6375/commit/7a9ae11ee94f2c1fb0d8d112afdb0f22398f61b2
Usage of boeffla_wl_blocker is strictly restricted, wakelocks exist for a reason.

https://github.com/AswinOP/kernel_xiaomi_sm6375/commit/3a5f7e2b0500928d8a80596c3fa07e2f98820433
Do a linux-upstream/ACK-upstream merges rather than cherry-picking the upstream merge commits.

https://github.com/AswinOP/kernel_xiaomi_sm6375/commit/8b7797806e631e44252a6444ee6f210045ce4e0c
https://github.com/AswinOP/kernel_xiaomi_sm6375/commit/2d164f8fc9e129301e798de13229ab077090a163
NO! We don't support KernelSU or do any support for exploitations.

Hence I'm marking the kernel as rejected.

**Comment by kawaaii** [comment]
https://github.com/AswinOP/device_xiaomi_veux/commit/5d3e2ea60c5af7f8599c63573a6e7fc4fe6cb7c8
No we don't suggest to enable adb on boot, and this is usually handled by USB init scripts.

https://github.com/AswinOP/device_xiaomi_veux/commit/462274288decdc9e51d82693d8a39a86bce6115b
You are even pinning the blobs which you are not shipping.

https://github.com/AswinOP/device_xiaomi_veux/commit/c173929df06f63d346a4a44e0e9719f5afebfb0e
We don't even use Smart Pixel overlays.

https://github.com/AswinOP/device_xiaomi_veux/commit/16cfda48c6fb78633db9d4e85f73993418a470a4
LLVM is used by default for kernel compilation.

https://github.com/AswinOP/device_xiaomi_veux/commit/be46010c38c974024bc467e9229a5770228c1f66
Cherrypick only the required changes than merging the whole other tree.

Looking at these changes, and after a long internal discussions we have decided to reject your application for official PixelOS maintainership.
Hope you would correct these mistakes and apply again next time after being more experienced.

**Comment by AswinOP** [comment]
Thanks for checking out my forum! I really appreciate your feedback and the pointers you've given me. I'll definitely make those changes and re-apply in future.
