### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by samrth012** [PixelOS-AOSP/official_devices#394]
## Name and Codename of the device you want to apply for 
```
Nothing Phone 2 ( Pong)
```

## Device Tree sources

```
https://github.com/samrth012/android_device_nothing_Pong.git
https://gitlab.com/samrth012/vendor_nothing_Pong.git
https://github.com/samrth012/kernel_nothing_sm8475.git
```

## What ROM's do you maintain officially/unofficially
```
RisingOS ( Unofficial)
```

## How long have you been building Custom ROMs
```
2 years
```

## Any Exceptions/special concern?
```
I have been working with kartikey, a friend of mine and we both agreed for me to apply for official, and we have been sharing a server so there are commits from his account, but that can be confirmed via telegram chat, in case of doubts.
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
samrth012
```

### Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-0-unofficial-pong-pixelos.4683832/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/NothingPhone2/410191
```

**Comment by whyredfire** [comment]
Hi, here's your review.

1. You are using a patch in `device/qcom/sepolicy_vndr` in your vendorsetup.sh which you did not mention in the application.

```
List of changes/patches applied to source, if any
No
```

https://github.com/samrth012/android_device_nothing_Pong/blob/4508104dfa202c253aaedfcf5ce62ba4c59aa8b9/vendorsetup.sh#L40-L45
```
echo 'Pick Sepolicy Commit'
# device/qcom/sepolicy_vndr
cd device/qcom/sepolicy_vndr/sm8450
git fetch https://github.com/Nothing-phone-2-Development/android_device_qcom_sepolicy_vndr
git cherry-pick d9fa2f5f3c36dae723d9ca0899dc0ab85e149e9d
cd ../../../../
```

Display hal is being cloned from somewhere else too which was not mentioned.

https://github.com/samrth012/android_device_nothing_Pong/blob/4508104dfa202c253aaedfcf5ce62ba4c59aa8b9/vendorsetup.sh#L21-L24
```
echo 'Cloning Display-Hal'
# hardware/qcom-caf/sm8450/display
rm -rf hardware/qcom-caf/sm8450/display
git clone --depth=1 https://github.com/Nothing-phone-2-Development/android_hardware_qcom_display.git hardware/qcom-caf/sm8450/display
```

The above violates 1.8 of the maintainer requirements.

2. Shipping KSU is against the rules as well

https://github.com/samrth012/android_device_nothing_Pong/blob/4508104dfa202c253aaedfcf5ce62ba4c59aa8b9/vendorsetup.sh#L7-L11
```
echo 'Adding KSU'
# kernel/nothing/sm8475
cd kernel/nothing/sm8475
curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
cd ../../../
```

3. You should write your commit messages properly.
For example:
Bad commit message: [Update README.md](https://github.com/samrth012/android_device_nothing_Pong/commit/943bad220f14a53d202bc1c4bd4b4d1a1b7d241d)
Good commit message: `Pong: Update device spec sheet`

4.
```
Any Exceptions/special concern?
I have been working with kartikey, a friend of mine and we both agreed for me to apply for official, and we have been sharing a server so there are commits from his account, but that can be confirmed via telegram chat, in case of doubts.
```
This isn't something we're okay with, sharing a server is fine and we don't really have a problem with that, `so there are commits from his account` but this sounds bad. If it's your work then it be under your name.

Also, since he's a friend, you can ask him for the changes that were suggested to him when he applied for the same. I highly suggest your rebase your tree again.
